version: '3'
services:
  app:
    build:
      args:
        REMOTE_CONTAINER: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow container management
      - vscode-server-extensions:/root/.vscode-server/extensions  # Cache user Vscode extensions
      - vscode-server-insider-extensions:/root/.vscode-server-insiders/extensions  # Cache core Vscode extensions
    command: tail -f /dev/null
volumes:
  vscode-server-extensions:
  vscode-server-insider-extensions:
